FROM ghcr.io/astral-sh/uv:debian-slim
RUN apt-get update && apt-get install -y ffmpeg curl
WORKDIR /app
COPY common/pyproject.toml common/pyproject.toml
COPY common/uv.lock common/uv.lock
COPY common/src common/src 
COPY pi/pyproject.toml pi/pyproject.toml
COPY pi/uv.lock pi/uv.lock
RUN uv --project pi sync
COPY pi/main.py pi/main.py
COPY pi/stream.py pi/stream.py
COPY pi/sensor.py pi/sensor.py
COPY pi/system.py pi/system.py
ENV PYTHONUNBUFFERED=1
ENV FASTAPI_MODE=run
CMD sh -c 'while true; do  curl --silent --retry 5 --retry-connrefused -H "Content-Type: application/json" -d "{\"name\": \"$NAME\", \"url\": \"$URL\"}" "$REGISTER_URL"; sleep 60; done & uv --project pi run fastapi ${FASTAPI_MODE} pi/main.py --port $PORT --host 0.0.0.0'
